## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [16]:
import os
import numpy as np
import pandas as pd

In [17]:
# 設定 data_path
dir_data = 'C:/Users/鍾雅欣/Documents/GitHub/Data'

In [18]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: C:/Users/鍾雅欣/Documents/GitHub/Data\application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [19]:
app_train.shape

(307511, 122)

#### 列出所有欄位

In [24]:
app_train.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [44]:
app_train[(app_train['TARGET']==1) & (app_train['CODE_GENDER']=='M')]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
40,100047,1,Cash loans,M,N,Y,0,202500.0,1193580.0,35028.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,4.0
94,100112,1,Cash loans,M,Y,Y,0,315000.0,953460.0,64107.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
138,100160,1,Cash loans,M,N,Y,0,292500.0,675000.0,36747.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
180,100209,1,Revolving loans,M,N,Y,3,180000.0,540000.0,27000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
246,100286,1,Cash loans,M,Y,Y,1,121500.0,263686.5,17298.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
255,100295,1,Cash loans,M,Y,N,1,225000.0,1019205.0,31032.0,...,1,0,0,0,0.0,0.0,0.0,6.0,0.0,1.0
260,100300,1,Cash loans,M,N,N,0,63000.0,426645.0,22468.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
261,100301,1,Cash loans,M,N,Y,1,112500.0,571486.5,31131.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,2.0
283,100326,1,Cash loans,M,Y,Y,0,36000.0,284400.0,10849.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
344,100396,1,Cash loans,M,N,N,0,112500.0,417024.0,25330.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
368,100424,1,Cash loans,M,N,Y,0,112500.0,117162.0,12433.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
381,100439,1,Cash loans,M,N,Y,0,81000.0,312840.0,22891.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
389,100452,1,Cash loans,M,N,Y,1,171000.0,1009566.0,36391.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
408,100472,1,Cash loans,M,Y,Y,1,135000.0,545040.0,26509.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
413,100477,1,Cash loans,M,Y,Y,1,112500.0,284400.0,22599.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
419,100485,1,Revolving loans,M,Y,N,1,270000.0,810000.0,40500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
424,100490,1,Cash loans,M,N,N,0,135000.0,755190.0,38686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
477,100547,1,Cash loans,M,Y,N,0,211500.0,450000.0,21888.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
492,100567,1,Revolving loans,M,Y,Y,0,99000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
534,100616,1,Cash loans,M,Y,N,0,225000.0,203760.0,22072.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
555,100641,1,Cash loans,M,N,Y,0,112500.0,254700.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
560,100646,1,Cash loans,M,Y,Y,0,216000.0,640080.0,31261.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
564,100650,1,Cash loans,M,N,N,0,135000.0,808650.0,31333.5,...,0,0,0,0,0.0,0.0,0.0,3.0,0.0,2.0
586,100672,1,Cash loans,M,N,Y,0,112500.0,808650.0,26217.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
627,100717,1,Cash loans,M,N,Y,0,135000.0,284400.0,13833.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
726,100839,1,Cash loans,M,N,N,0,180000.0,824823.0,29353.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
727,100840,1,Cash loans,M,Y,Y,0,135000.0,450000.0,30442.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
866,100992,1,Cash loans,M,N,N,2,135000.0,203760.0,13396.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
921,101063,1,Cash loans,M,Y,N,2,202500.0,755190.0,38686.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306660,455298,1,Cash loans,M,Y,Y,0,135000.0,1327500.0,38812.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306676,455314,1,Cash loans,M,Y,Y,0,225000.0,790830.0,62613.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
306688,455330,1,Cash loans,M,Y,Y,0,135000.0,130500.0,13833.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
306710,455352,1,Cash loans,M,N,Y,1,450000.0,781920.0,42547.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
306745,455392,1,Cash loans,M,N,Y,0,193500.0,283500.0,22396.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306786,455443,1,Cash loans,M,N,Y,2,202500.0,247275.0,22810.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
306813,455470,1,Cash loans,M,N,Y,2,225000.0,906228.0,38524.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
306815,455472,1,Cash loans,M,N,Y,0,315000.0,675000.0,53460.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
306939,455611,1,Cash loans,M,Y,Y,0,135000.0,986553.0,35082.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306946,455618,1,Cash loans,M,Y,Y,0,126000.0,143910.0,15628.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
306971,455649,1,Cash loans,M,N,Y,0,90000.0,265851.0,16195.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307001,455681,1,Cash loans,M,Y,N,0,180000.0,835380.0,35523.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307082,455772,1,Cash loans,M,Y,Y,2,76500.0,545040.0,26640.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307096,455786,1,Cash loans,M,Y,N,1,202500.0,1067418.0,31207.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307097,455788,1,Cash loans,M,N,N,0,126000.0,207396.0,8577.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307123,455819,1,Cash loans,M,Y,Y,1,225000.0,1149628.5,48838.5,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,2.0
307126,455822,1,Cash loans,M,Y,N,2,112500.0,450000.0,30573.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307162,455865,1,Cash loans,M,N,N,0,180000.0,450000.0,30573.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
307177,455880,1,Cash loans,M,N,N,0,135000.0,260640.0,28197.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307266,455983,1,Cash loans,M,Y,N,0,189000.0,604413.0,25537.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307268,455985,1,Cash loans,M,N,N,0,135000.0,355536.0,19417.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307283,456000,1,Cash loans,M,Y,Y,0,130500.0,306306.0,13108.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
307310,456034,1,Cash loans,M,N,Y,0,90000.0,490536.0,23989.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307328,456052,1,Cash loans,M,Y,N,1,135000.0,316125.0,15372.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307377,456102,1,Cash loans,M,N,Y,0,67500.0,313438.5,20943.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307433,456171,1,Cash loans,M,N,Y,0,50400.0,113760.0,7731.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
307438,456176,1,Cash loans,M,N,Y,0,171000.0,1436850.0,42142.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307446,456184,1,Cash loans,M,N,N,0,270000.0,900000.0,40671.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307448,456186,1,Cash loans,M,N,N,1,207000.0,450000.0,32746.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307481,456225,1,Cash loans,M,N,Y,0,225000.0,297000.0,19975.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子